apiVersion: v1
kind: Pod
metadata:
  name: model-store-pod3
spec:
  volumes:
    - name: model-store
      persistentVolumeClaim:
        claimName: task-pv-claim3
  containers:
    - name: model-store
      image: ubuntu
      command: [ "sleep" ]
      args: [ "infinity" ]
      volumeMounts:
        - mountPath: "/pv"
          name: model-store
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"